name: Build & Release

on: [push]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

jobs:
  github-release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
        arch: [x64, arm64, arm]
        exclude:
          - os: macos-15
            arch: arm
          - os: macos-15
            arch: x64
          - os: windows-2025
            arch: arm
          - os: windows-2025
            arch: arm64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Install libarchive-tools for pacman build # Related https://github.com/electron-userland/electron-builder/issues/4181
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libarchive-tools

      - name: Install dependencies
        run: yarn --link-duplicates --pure-lockfile

      - name: Build for test only linux
        if: |
          github.ref != 'refs/heads/main' &&
          startsWith(matrix.os, 'ubuntu')
        run: yarn dist:linux:${{ matrix.arch }} -- --publish never

      - name: Release linux
        if: |
          github.ref == 'refs/heads/main' &&
          startsWith(matrix.os, 'ubuntu')
        run: yarn dist:linux:${{ matrix.arch }} -- --publish always

      - name: Build for test only macos
        if: |
          github.ref != 'refs/heads/main' &&
          startsWith(matrix.os, 'macos')
        run: yarn dist:mac -- --publish never

      - name: Release macos
        if: |
          github.ref == 'refs/heads/main' &&
          startsWith(matrix.os, 'macos')
        run: yarn dist:mac -- --publish always

      - name: Build for test only windows
        if: |
          github.ref != 'refs/heads/main' &&
          startsWith(matrix.os, 'windows')
        run: yarn dist:windows -- --publish never

      - name: Release windows
        if: |
          github.ref == 'refs/heads/main' &&
          startsWith(matrix.os, 'windows')
        run: yarn dist:windows -- --publish always
